kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /Users/tomas_escoru/mydev/my-first-operator/tmp/wbc-test
    containerPath: /tmp/wbc-test
  - hostPath: /Users/tomas_escoru/mydev/my-first-operator/tmp/wbc-test-dest
    containerPath: /tmp/wbc-test-dest
