# This rule is not used by the project my-first-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over snapshot.wbc.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: my-first-operator
    app.kubernetes.io/managed-by: kustomize
  name: wbcsnapshot-admin-role
rules:
- apiGroups:
  - snapshot.wbc.com
  resources:
  - wbcsnapshots
  verbs:
  - '*'
- apiGroups:
  - snapshot.wbc.com
  resources:
  - wbcsnapshots/status
  verbs:
  - get
