# This rule is not used by the project my-first-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to snapshot.wbc.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: my-first-operator
    app.kubernetes.io/managed-by: kustomize
  name: wbcsnapshot-viewer-role
rules:
- apiGroups:
  - snapshot.wbc.com
  resources:
  - wbcsnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.wbc.com
  resources:
  - wbcsnapshots/status
  verbs:
  - get
